### ISSUE TITLE
IndexOutOfBoundsException on LoveTropics server

### ISSUE THREAD

**Issue by Trikzon** [Tropicraft/SurvivalPlus#6]
I'm getting an IndexOutOfBoundsException using the LoveTropics modpack while in the build menu.

```
at com.lovetropics.gamemodebuild.container.BuildScreen.mouseClicked(BuildScreen.java:140)
```

https://github.com/LoveTropics/GamemodeBuild/blob/master/src/main/java/com/lovetropics/gamemodebuild/container/BuildScreen.java#L140

I'm on linux, so I assume that has something to do with a bad mouse position.

https://pastebin.com/wPDcLS42

**Comment by davidpanic** [comment]
This still seems to be present in the LoveTropics 2021 version (1.1.3)

[crash-2021-11-07_02.31.50-client.txt](https://github.com/LoveTropics/GamemodeBuild/files/7491547/crash-2021-11-07_02.31.50-client.txt)

Using Artix Linux kernel 5.14.12 built @ 2021-11-01 18:34:29, mention me if more info and/or debugging is required.

**Comment by sekwah41** [comment]
Should focus on func_241440_b_ in Container. That seems to be the second error thrown at least.

By the looks of it, it may be due to null or not properly registered item slots, but most of the loops use the current size.

**Comment by sekwah41** [comment]
![image](https://github.com/LoveTropics/GamemodeBuild/assets/3209834/198ce834-913e-45b8-8083-b98dec944db1)

On the inventory slots 45 and above are normal building slots. It seem there may be some behaviour where the inventory slots are not properly set hence inxed out of bounds.

**Comment by sekwah41** [comment]
If anyone is able to give more info on how to replicate this or give any more specifics as to when this triggers that would be a major help.

Im going to mess around with this a little then try using https://github.com/jagt/clumsy to simulate some network lag and see if its possible an issue that is harder to replicate locally.

**Comment by Trikzon** [comment]
It was three years ago now since I had this issue and initially reported it and I'm now on a different machine and OS than I was, so take this with a grain of salt.

But I think I remember being able to get this crash in a single player world leading me to believe that an unstable network shouldn't affect this issue

**Comment by davidpanic** [comment]
@Trikzon Not necessarily. A singleplayer world still has a local "server" running with only you connecting to it. You're still doing networking, but only locally.

**Comment by sekwah41** [comment]
Though if you were able to trigger it on single player that may mean ping has less of a bearing on having the issue occour.

**Comment by sekwah41** [comment]
I think we should put fixing this issue on hold until we are able to repeat it in the latest version, hopefully with a reliable way to reproduce the bug.
