### ISSUE TITLE
Can only trash items that were directly taken out of the build menu

### ISSUE THREAD

**Issue by Trikzon** [Tropicraft/SurvivalPlus#7]
If a block is placed and then broken, the dropped item can't be returned to the build menu. Items taken out of the menu can be. This becomes annoying when building because a player ends up with many blocks that can't be easily trashed and has to throw them on the ground.

I see that this is intended due to [this comment](https://github.com/LoveTropics/GamemodeBuild/blob/1.16/src/main/java/com/lovetropics/gamemodebuild/container/BuildContainer.java#L169), but in my opinion this should be reassessed.

**Comment by tterrag1098** [comment]
The intention was for that to be used in combination with doTileDrops=false. But it should be configurable at least.

**Comment by sekwah41** [comment]
Made a pr which will avoid you being able to get items not from the build mode menu unless its from a chest. Though I don't think the main issue of the items dropping will be a problem as I believe we have block drops off usually?

Either way, should help.
